[package]
name = "sim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rand = "0.9"
sdl2 = { version = "0.37", features = ["image"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
