[package]
name = "sim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
lazy_static = "1"
rand = "0.8.5"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["image"]
